Fix "'str' has no attribute 'value_for_protocol'"
AttributeError: 'str' object has no attribute 'value_for_protocol'
This is because I passed the unparsed argument `preferred_nodes` to `Node`.
`trinity_config.preferred_nodes` is what should be passed to `Node`.