Reproduce: "object has no attribute 'parent_hash'"
Something about running the beam sync test at block 5 reproducibly gives
this error:
AttributeError: 'PetersburgBlock' object has no attribute 'parent_hash'

(I have run the full range before, so this is "new" at least since beam
sync started working)

Rough stack trace:

   trinity/sync/beam/chain.py:212: in run
       await self._download_blocks(final_headers[0])
   trinity/sync/beam/chain.py:284: in _download_blocks
       await manager.wait_finished()
   venv/lib/python3.7/site-packages/async_generator/_util.py:42: in __aexit__
       await self._agen.asend(None)
   venv/lib/python3.7/site-packages/async_service/asyncio.py:444: in background_asyncio_service
       for _, exc_value, exc_tb in manager._errors
   venv/lib/python3.7/site-packages/async_service/base.py:300: in _run_and_manage_task
       await task.run()
   venv/lib/python3.7/site-packages/async_service/asyncio.py:35: in run
       await self._async_fn(*self._async_fn_args)
   trinity/sync/full/chain.py:620: in run
       self._block_persist_tracker.set_finished_dependency(head)

   > dependency_id = self._dependency_of(finished_task)

I am running a few custom things locally (py-trie v2a1, a custom
py-evm), so I wanted to use CI to confirm that this isn't some local
ghost I'm chasing among my changeset, because it looks totally
unrelated.