Use 2nd method to make timeout & xdist coexist
It turns out that "test failures aren't as readable" means that it's
impossible to even tell which test caused the timeout, making it pretty
much useless.

See both workaround methods here:
https://github.com/postlund/pyatv/issues/904

Timeout looked like:

py38-eth1-core run-test: commands[0] | pytest --forked -n 4 tests/core/
============================= test session starts ==============================
platform linux -- Python 3.8.8, pytest-5.3.5, py-1.10.0, pluggy-0.13.1
cachedir: .tox/py38-eth1-core/.pytest_cache
Using --randomly-seed=3901568775
rootdir: /home/circleci/repo, inifile: pytest.ini
plugins: Faker-6.6.2, anyio-2.2.0, hypothesis-4.57.1, aiohttp-0.3.0, asyncio-0.10.0, cov-2.11.1, forked-1.3.0, mock-1.12.1, randomly-3.5.0, timeout-1.4.2, xdist-1.34.0, web3-5.17.0
timeout: 300.0s
timeout method: thread
timeout func_only: False
gw0 I / gw1 I / gw2 I / gw3 Igw0 C / gw1 I / gw2 I / gw3 Igw0 C / gw1 C / gw2 I / gw3 Igw0 C / gw1 C / gw2 C / gw3 Igw0 C / gw1 C / gw2 C / gw3 Cgw0 C / gw1 C / gw2 ok / gw3 Cgw0 ok / gw1 C / gw2 ok / gw3 Cgw0 ok / gw1 ok / gw2 ok / gw3 Cgw0 ok / gw1 ok / gw2 ok / gw3 okgw0 ok / gw1 ok / gw2 [710] / gw3 okgw0 [710] / gw1 ok / gw2 [710] / gw3 okgw0 [710] / gw1 ok / gw2 [710] / gw3 [710]gw0 [710] / gw1 [710] / gw2 [710] / gw3 [710]
........................................................................ [ 10%]
........................................................................ [ 20%]
........................................................................ [ 30%]
........................................................................ [ 40%]
........................................................................ [ 50%]
........................................................................ [ 60%]
..........................s.................s........................... [ 70%]
........................................................................ [ 81%]
........................................................................ [ 91%]
.........................................................
+++++++++++++++++++++++++++++++++++ Timeout ++++++++++++++++++++++++++++++++++++

~~~~~~~~~~~~~~~~~~~~~ Stack of <unknown> (139863545100032) ~~~~~~~~~~~~~~~~~~~~~
  File "/home/circleci/repo/.tox/py38-eth1-core/lib/python3.8/site-packages/execnet/gateway_base.py", line 285, in _perform_spawn
    reply.run()
  File "/home/circleci/repo/.tox/py38-eth1-core/lib/python3.8/site-packages/execnet/gateway_base.py", line 220, in run
    self._result = func(*args, **kwargs)
  File "/home/circleci/repo/.tox/py38-eth1-core/lib/python3.8/site-packages/execnet/gateway_base.py", line 967, in _thread_receiver
    msg = Message.from_io(io)
  File "/home/circleci/repo/.tox/py38-eth1-core/lib/python3.8/site-packages/execnet/gateway_base.py", line 432, in from_io
    header = io.read(9)  # type 1, channel 4, payload 4
  File "/home/circleci/repo/.tox/py38-eth1-core/lib/python3.8/site-packages/execnet/gateway_base.py", line 400, in read
    data = self._read(numbytes - len(buf))

~~~~~~~~~~~~~~~~~~~~ Stack of MainThread (139863548573504) ~~~~~~~~~~~~~~~~~~~~~
  File "<string>", line 1, in <module>
  File "<string>", line 8, in <module>
  File "/home/circleci/repo/.tox/py38-eth1-core/lib/python3.8/site-packages/execnet/gateway_base.py", line 1554, in serve
    WorkerGateway(io=io, id=id, _startcount=2).serve()
  File "/home/circleci/repo/.tox/py38-eth1-core/lib/python3.8/site-packages/execnet/gateway_base.py", line 1060, in serve
    self._execpool.integrate_as_primary_thread()
  File "/home/circleci/repo/.tox/py38-eth1-core/lib/python3.8/site-packages/execnet/gateway_base.py", line 267, in integrate_as_primary_thread
    self._perform_spawn(reply)
  File "/home/circleci/repo/.tox/py38-eth1-core/lib/python3.8/site-packages/execnet/gateway_base.py", line 285, in _perform_spawn
    reply.run()
  File "/home/circleci/repo/.tox/py38-eth1-core/lib/python3.8/site-packages/execnet/gateway_base.py", line 220, in run
    self._result = func(*args, **kwargs)
  File "/home/circleci/repo/.tox/py38-eth1-core/lib/python3.8/site-packages/execnet/gateway_base.py", line 1084, in executetask
    do_exec(co, loc)  # noqa
  File "/home/circleci/repo/.tox/py38-eth1-core/lib/python3.8/site-packages/xdist/remote.py", line 273, in <module>
    config.hook.pytest_cmdline_main(config=config)
  File "/home/circleci/repo/.tox/py38-eth1-core/lib/python3.8/site-packages/pluggy/hooks.py", line 286, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File "/home/circleci/repo/.tox/py38-eth1-core/lib/python3.8/site-packages/pluggy/manager.py", line 93, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "/home/circleci/repo/.tox/py38-eth1-core/lib/python3.8/site-packages/pluggy/manager.py", line 84, in <lambda>
    self._inner_hookexec = lambda hook, methods, kwargs: hook.multicall(
  File "/home/circleci/repo/.tox/py38-eth1-core/lib/python3.8/site-packages/pluggy/callers.py", line 187, in _multicall
    res = hook_impl.function(*args)
  File "/home/circleci/repo/.tox/py38-eth1-core/lib/python3.8/site-packages/_pytest/main.py", line 240, in pytest_cmdline_main
    return wrap_session(config, _main)
  File "/home/circleci/repo/.tox/py38-eth1-core/lib/python3.8/site-packages/_pytest/main.py", line 197, in wrap_session
    session.exitstatus = doit(config, session) or 0
  File "/home/circleci/repo/.tox/py38-eth1-core/lib/python3.8/site-packages/_pytest/main.py", line 247, in _main
    config.hook.pytest_runtestloop(session=session)
  File "/home/circleci/repo/.tox/py38-eth1-core/lib/python3.8/site-packages/pluggy/hooks.py", line 286, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File "/home/circleci/repo/.tox/py38-eth1-core/lib/python3.8/site-packages/pluggy/manager.py", line 93, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "/home/circleci/repo/.tox/py38-eth1-core/lib/python3.8/site-packages/pluggy/manager.py", line 84, in <lambda>
    self._inner_hookexec = lambda hook, methods, kwargs: hook.multicall(
  File "/home/circleci/repo/.tox/py38-eth1-core/lib/python3.8/site-packages/pluggy/callers.py", line 187, in _multicall
    res = hook_impl.function(*args)
  File "/home/circleci/repo/.tox/py38-eth1-core/lib/python3.8/site-packages/xdist/remote.py", line 71, in pytest_runtestloop
    self.run_one_test(torun)
  File "/home/circleci/repo/.tox/py38-eth1-core/lib/python3.8/site-packages/xdist/remote.py", line 88, in run_one_test
    self.config.hook.pytest_runtest_protocol(item=item, nextitem=nextitem)
  File "/home/circleci/repo/.tox/py38-eth1-core/lib/python3.8/site-packages/pluggy/hooks.py", line 286, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File "/home/circleci/repo/.tox/py38-eth1-core/lib/python3.8/site-packages/pluggy/manager.py", line 93, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "/home/circleci/repo/.tox/py38-eth1-core/lib/python3.8/site-packages/pluggy/manager.py", line 84, in <lambda>
    self._inner_hookexec = lambda hook, methods, kwargs: hook.multicall(
  File "/home/circleci/repo/.tox/py38-eth1-core/lib/python3.8/site-packages/pluggy/callers.py", line 187, in _multicall
    res = hook_impl.function(*args)
  File "/home/circleci/repo/.tox/py38-eth1-core/lib/python3.8/site-packages/pytest_forked/__init__.py", line 46, in pytest_runtest_protocol
    reports = forked_run_report(item)
  File "/home/circleci/repo/.tox/py38-eth1-core/lib/python3.8/site-packages/pytest_forked/__init__.py", line 68, in forked_run_report
    result = ff.waitfinish()
  File "/home/circleci/repo/.tox/py38-eth1-core/lib/python3.8/site-packages/py/_process/forkedfunc.py", line 82, in waitfinish
    pid, systemstatus = waiter(self.pid, 0)

+++++++++++++++++++++++++++++++++++ Timeout ++++++++++++++++++++++++++++++++++++
ERROR: Got SIGTERM, handling it as a KeyboardInterrupt
ERROR: got KeyboardInterrupt signal

Too long with no output (exceeded 10m0s): context deadline exceeded